### ISSUE TITLE
Upgrade Failing

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/bookstack_ynh#50]
I attempted to update today but it failed—here are the logs for reference:

https://paste.yunohost.org/raw/ayuzejiros

**Comment by ericgaspar** [comment]
`Unable to install core dependencies with Composer.` I wonder if it is related to the PHP8 upgrade...
Can you try this branch that keeps PHP7.3 ?
`sudo yunohost app upgrade bookstack -u https://github.com/YunoHost-Apps/bookstack_ynh/tree/7.3 --debug`

**Comment by brimwats** [comment]
I thought that might be it too! But no luck: https://paste.yunohost.org/raw/hovuguyajo

**Comment by brimwats1** [comment]
I tried it again since the php update and didn't have any luck

**Comment by brimwats** [comment]
I tried it again since the php update and didn't have any luck

**Comment by VonKavalier** [comment]
Got the same error when trying to update from `21.05.3~ynh1` to `21.12.5~ynh1`

Here is my ynh version:
```
yunohost:
  repo: stable
  version: 4.3.6.2
yunohost-admin:
  repo: testing
  version: 4.3.4.1
moulinette:
  repo: stable
  version: 4.3.3.1
ssowat:
  repo: stable
  version: 4.3.3.1
```

**Comment by OniriCorpe** [comment]
I've this issue too.
(from 21.05.3~ynh1 to 22.02.3~ynh1)

```
yunohost:
  repo: stable
  version: 4.3.6.2
yunohost-admin:
  repo: testing
  version: 4.3.4.1
moulinette:
  repo: stable
  version: 4.3.3.1
ssowat:
  repo: stable
  version: 4.3.3.1
```
